//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualVisioSVGLight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualVisioSVGLight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationInfos64 {
            get {
                object obj = ResourceManager.GetObject("ApplicationInfos64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationOptions64 {
            get {
                object obj = ResourceManager.GetObject("ApplicationOptions64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConvertSVG {
            get {
                object obj = ResourceManager.GetObject("ConvertSVG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export64 {
            get {
                object obj = ResourceManager.GetObject("Export64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileManagement64 {
            get {
                object obj = ResourceManager.GetObject("FileManagement64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access database error: {0}, Database : {1}, Utilisateur : {2}.
        /// </summary>
        internal static string idsAccessDatabaseError {
            get {
                return ResourceManager.GetString("idsAccessDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsApplicationInternalName {
            get {
                return ResourceManager.GetString("idsApplicationInternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsApplicationMenuBar {
            get {
                return ResourceManager.GetString("idsApplicationMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsApplicationName {
            get {
                return ResourceManager.GetString("idsApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsApplicationToolbar {
            get {
                return ResourceManager.GetString("idsApplicationToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes have been made, do you want to save them?.
        /// </summary>
        internal static string idsAskProjectSave {
            get {
                return ResourceManager.GetString("idsAskProjectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareVisual.
        /// </summary>
        internal static string idsCompanyName {
            get {
                return ResourceManager.GetString("idsCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the active project?.
        /// </summary>
        internal static string idsConfirmDelete {
            get {
                return ResourceManager.GetString("idsConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access provider error.
        /// </summary>
        internal static string idsDataBaseError {
            get {
                return ResourceManager.GetString("idsDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsDatabaseName {
            get {
                return ResourceManager.GetString("idsDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabasePath.
        /// </summary>
        internal static string idsDatabasePathKey {
            get {
                return ResourceManager.GetString("idsDatabasePathKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Dev\VisualVisioSVGLight\VisualVisioSVGLight\System.
        /// </summary>
        internal static string idsDefaultDatabasePath {
            get {
                return ResourceManager.GetString("idsDefaultDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLEXPRESS.
        /// </summary>
        internal static string idsDefaultDataSource {
            get {
                return ResourceManager.GetString("idsDefaultDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsDefaultInitialCatalog {
            get {
                return ResourceManager.GetString("idsDefaultInitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur.
        /// </summary>
        internal static string idsDefaultMode {
            get {
                return ResourceManager.GetString("idsDefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsDefaultPassword {
            get {
                return ResourceManager.GetString("idsDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESS2007.
        /// </summary>
        internal static string idsDefaultProvider {
            get {
                return ResourceManager.GetString("idsDefaultProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsDefaultUser {
            get {
                return ResourceManager.GetString("idsDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;VisualVisioSVGLight : &quot;.
        /// </summary>
        internal static string idsDocumentTitle {
            get {
                return ResourceManager.GetString("idsDocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur {0}, {1}, {2}, {3}.
        /// </summary>
        internal static string idsErreurApp4 {
            get {
                return ResourceManager.GetString("idsErreurApp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opened project.
        /// </summary>
        internal static string idsErrorNoProjectOpened {
            get {
                return ResourceManager.GetString("idsErrorNoProjectOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing document error {0}.
        /// </summary>
        internal static string idsErrorPublish {
            get {
                return ResourceManager.GetString("idsErrorPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding shape:  {0}.
        /// </summary>
        internal static string idsErrorShapeAdd {
            get {
                return ResourceManager.GetString("idsErrorShapeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the database directory.
        /// </summary>
        internal static string idsFdOpenTitleOptionPath {
            get {
                return ResourceManager.GetString("idsFdOpenTitleOptionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file error {0} .
        /// </summary>
        internal static string idsFileNotFound {
            get {
                return ResourceManager.GetString("idsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        internal static string idsFolderNameDefaultValue {
            get {
                return ResourceManager.GetString("idsFolderNameDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string idsFolderNameKey {
            get {
                return ResourceManager.GetString("idsFolderNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file {0} not found.
        /// </summary>
        internal static string idsHelpfileNotFound {
            get {
                return ResourceManager.GetString("idsHelpfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The active document is not a VisualVisioSVGLight document .
        /// </summary>
        internal static string idsInvalidDocumentType {
            get {
                return ResourceManager.GetString("idsInvalidDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About VisualVisioSVGLight....
        /// </summary>
        internal static string idsMenuItemAbout {
            get {
                return ResourceManager.GetString("idsMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagProcessDesignerItemAbout.
        /// </summary>
        internal static string idsMenuItemAboutTag {
            get {
                return ResourceManager.GetString("idsMenuItemAboutTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details on VisualVisioSVGLight.
        /// </summary>
        internal static string idsMenuItemAboutTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemAboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string idsMenuItemDisplay {
            get {
                return ResourceManager.GetString("idsMenuItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string idsMenuItemDocument {
            get {
                return ResourceManager.GetString("idsMenuItemDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        internal static string idsMenuItemDocumentNew {
            get {
                return ResourceManager.GetString("idsMenuItemDocumentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLightDocumentNew.
        /// </summary>
        internal static string idsMenuItemDocumentNewTag {
            get {
                return ResourceManager.GetString("idsMenuItemDocumentNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning of a document.
        /// </summary>
        internal static string idsMenuItemDocumentNewTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemDocumentNewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        internal static string idsMenuItemHelp {
            get {
                return ResourceManager.GetString("idsMenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLighttemHelp.
        /// </summary>
        internal static string idsMenuItemHelpTag {
            get {
                return ResourceManager.GetString("idsMenuItemHelpTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Online Help.
        /// </summary>
        internal static string idsMenuItemHelpTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string idsMenuItemNewImage {
            get {
                return ResourceManager.GetString("idsMenuItemNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string idsMenuItemOptions {
            get {
                return ResourceManager.GetString("idsMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLightItemOptions.
        /// </summary>
        internal static string idsMenuItemOptionsTag {
            get {
                return ResourceManager.GetString("idsMenuItemOptionsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing configuration options of VisualVisioSVGLight.
        /// </summary>
        internal static string idsMenuItemOptionsTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemOptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string idsMenuItemProject {
            get {
                return ResourceManager.GetString("idsMenuItemProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string idsMenuItemProjectNew {
            get {
                return ResourceManager.GetString("idsMenuItemProjectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLightProjectNew.
        /// </summary>
        internal static string idsMenuItemProjectNewTag {
            get {
                return ResourceManager.GetString("idsMenuItemProjectNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new project.
        /// </summary>
        internal static string idsMenuItemProjectNewTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemProjectNewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLightProject.
        /// </summary>
        internal static string idsMenuItemProjectTag {
            get {
                return ResourceManager.GetString("idsMenuItemProjectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects management.
        /// </summary>
        internal static string idsMenuItemProjectTooltip {
            get {
                return ResourceManager.GetString("idsMenuItemProjectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagVisualVisioSVGLightMenu.
        /// </summary>
        internal static string idsMenuTag {
            get {
                return ResourceManager.GetString("idsMenuTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsMenuTitle {
            get {
                return ResourceManager.GetString("idsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application menu VisualVisioSVGLight.
        /// </summary>
        internal static string idsMenuTooltip {
            get {
                return ResourceManager.GetString("idsMenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart Visio for modification to take effects.
        /// </summary>
        internal static string idsNeedToRestart {
            get {
                return ResourceManager.GetString("idsNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project selected.
        /// </summary>
        internal static string idsNoProjectSelected {
            get {
                return ResourceManager.GetString("idsNoProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not yet available.
        /// </summary>
        internal static string idsNotImplemented {
            get {
                return ResourceManager.GetString("idsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document nul !!!.
        /// </summary>
        internal static string idsNullActiveDoc {
            get {
                return ResourceManager.GetString("idsNullActiveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visApp nul !!!.
        /// </summary>
        internal static string idsNullApp {
            get {
                return ResourceManager.GetString("idsNullApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visDocument du VisualVisioSVGLight doc nul !!!.
        /// </summary>
        internal static string idsNullDoc {
            get {
                return ResourceManager.GetString("idsNullDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string idsOptions {
            get {
                return ResourceManager.GetString("idsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string idsOptionsKey {
            get {
                return ResourceManager.GetString("idsOptionsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string idsOptionsKeyCulture {
            get {
                return ResourceManager.GetString("idsOptionsKeyCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string idsOptionsKeyCultureDefaultValue {
            get {
                return ResourceManager.GetString("idsOptionsKeyCultureDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string idsPath {
            get {
                return ResourceManager.GetString("idsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project {0} already exists, cannot create it !!!.
        /// </summary>
        internal static string idsProjectAlreadyExist {
            get {
                return ResourceManager.GetString("idsProjectAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Dev\VisualVisioSVGLight\VisualVisioSVGLight\Projets.
        /// </summary>
        internal static string idsProjectDefaultValue {
            get {
                return ResourceManager.GetString("idsProjectDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        internal static string idsProjectKey {
            get {
                return ResourceManager.GetString("idsProjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION.
        /// </summary>
        internal static string idsProjectRoot {
            get {
                return ResourceManager.GetString("idsProjectRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La validation du projet a échoué, vérifiez dans les options du projet les valeurs suivantes: {0}.
        /// </summary>
        internal static string idsProjectValidationFailed {
            get {
                return ResourceManager.GetString("idsProjectValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string idsProvider {
            get {
                return ResourceManager.GetString("idsProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string idsPublishModeDefaultValue {
            get {
                return ResourceManager.GetString("idsPublishModeDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string idsPublishModeKey {
            get {
                return ResourceManager.GetString("idsPublishModeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export report.
        /// </summary>
        internal static string idsReportExportName {
            get {
                return ResourceManager.GetString("idsReportExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string idsReportTitle {
            get {
                return ResourceManager.GetString("idsReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsSPLibraryNameDefaultValue {
            get {
                return ResourceManager.GetString("idsSPLibraryNameDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPLibraryName.
        /// </summary>
        internal static string idsSPLibraryNameKey {
            get {
                return ResourceManager.GetString("idsSPLibraryNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string idsSPPortNumDefaultValue {
            get {
                return ResourceManager.GetString("idsSPPortNumDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPNumPort.
        /// </summary>
        internal static string idsSPPortNumKey {
            get {
                return ResourceManager.GetString("idsSPPortNumKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsSPServerNameDefaultValue {
            get {
                return ResourceManager.GetString("idsSPServerNameDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPServerName.
        /// </summary>
        internal static string idsSPServerNameKey {
            get {
                return ResourceManager.GetString("idsSPServerNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.
        /// </summary>
        internal static string idsSPSiteNameDefaultValue {
            get {
                return ResourceManager.GetString("idsSPSiteNameDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPSiteName.
        /// </summary>
        internal static string idsSPSiteNameKey {
            get {
                return ResourceManager.GetString("idsSPSiteNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Dev\VisualVisioSVGLight\VisualVisioSVGLight\Gabarits.
        /// </summary>
        internal static string idsStencilDefaultValue {
            get {
                return ResourceManager.GetString("idsStencilDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabarits.
        /// </summary>
        internal static string idsStencilKey {
            get {
                return ResourceManager.GetString("idsStencilKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabarits.
        /// </summary>
        internal static string idsStencilList {
            get {
                return ResourceManager.GetString("idsStencilList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.vssx.
        /// </summary>
        internal static string idsStencilListDefaultValue {
            get {
                return ResourceManager.GetString("idsStencilListDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.vssx.
        /// </summary>
        internal static string idsStencilName {
            get {
                return ResourceManager.GetString("idsStencilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Dev\VisualVisioSVGLight\VisualVisioSVGLight\System.
        /// </summary>
        internal static string idsSystemDefaultValue {
            get {
                return ResourceManager.GetString("idsSystemDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string idsSystemKey {
            get {
                return ResourceManager.GetString("idsSystemKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Dev\VisualVisioSVGLight\VisualVisioSVGLight\Modeles.
        /// </summary>
        internal static string idsTemplateDefaultValue {
            get {
                return ResourceManager.GetString("idsTemplateDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeles.
        /// </summary>
        internal static string idsTemplateKey {
            get {
                return ResourceManager.GetString("idsTemplateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualVisioSVGLight.vstx.
        /// </summary>
        internal static string idsTemplateName {
            get {
                return ResourceManager.GetString("idsTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string idsUserModeDefaultValue {
            get {
                return ResourceManager.GetString("idsUserModeDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMode.
        /// </summary>
        internal static string idsUserModeKey {
            get {
                return ResourceManager.GetString("idsUserModeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings of VisualVisioSVGLight application is different from Visio Language settings. You can correct this using VisualVisioSVGLight settings command..
        /// </summary>
        internal static string idsVisioLanguageDifference {
            get {
                return ResourceManager.GetString("idsVisioLanguageDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PDF64 {
            get {
                object obj = ResourceManager.GetObject("PDF64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectClose64 {
            get {
                object obj = ResourceManager.GetObject("ProjectClose64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectDelete64 {
            get {
                object obj = ResourceManager.GetObject("ProjectDelete64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectNew64 {
            get {
                object obj = ResourceManager.GetObject("ProjectNew64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectOpen64 {
            get {
                object obj = ResourceManager.GetObject("ProjectOpen64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectSave64 {
            get {
                object obj = ResourceManager.GetObject("ProjectSave64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectSaveAs64 {
            get {
                object obj = ResourceManager.GetObject("ProjectSaveAs64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report32 {
            get {
                object obj = ResourceManager.GetObject("Report32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Report64 {
            get {
                object obj = ResourceManager.GetObject("Report64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect numbering, the number modification will be ignored!!!.
        /// </summary>
        internal static string strBadNum {
            get {
                return ResourceManager.GetString("strBadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard ({0})|{1}.
        /// </summary>
        internal static string strCalculExtension {
            get {
                return ResourceManager.GetString("strCalculExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ({0})|{1}.
        /// </summary>
        internal static string strDocExtension {
            get {
                return ResourceManager.GetString("strDocExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing (*.vsdx;*.vsd;*.vdx)|*.vsdx;*.vsd;*.vdx.
        /// </summary>
        internal static string strFdFilterDrawing {
            get {
                return ResourceManager.GetString("strFdFilterDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image (*.png;*.bmp;*.gif)|*.png;*.bmp;*.gif.
        /// </summary>
        internal static string strFdLogoFilter {
            get {
                return ResourceManager.GetString("strFdLogoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found {0}, it cannot be opened.
        /// </summary>
        internal static string strIdsDocumentNotfound {
            get {
                return ResourceManager.GetString("strIdsDocumentNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}, {1}.
        /// </summary>
        internal static string strIdsErreurApp2 {
            get {
                return ResourceManager.GetString("strIdsErreurApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name.
        /// </summary>
        internal static string strIdsErreurBadProjectName {
            get {
                return ResourceManager.GetString("strIdsErreurBadProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t initialize the document: {1} {0} : {1}.
        /// </summary>
        internal static string strIdsErreurInitError {
            get {
                return ResourceManager.GetString("strIdsErreurInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the last document from the project.
        /// </summary>
        internal static string strIdsErrorCannotDeleteLast {
            get {
                return ResourceManager.GetString("strIdsErrorCannotDeleteLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        internal static string strIdsErrorProjectNotFound {
            get {
                return ResourceManager.GetString("strIdsErrorProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size is too long it will be tracked to 255 characters.
        /// </summary>
        internal static string strIdsErrorTruncated {
            get {
                return ResourceManager.GetString("strIdsErrorTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when saving the {0} project.
        /// </summary>
        internal static string strIdsErrorWhileSaving {
            get {
                return ResourceManager.GetString("strIdsErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application initial error  {0}.
        /// </summary>
        internal static string strIdsInitializationError {
            get {
                return ResourceManager.GetString("strIdsInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect valuer.
        /// </summary>
        internal static string strIdsInvalidEntry {
            get {
                return ResourceManager.GetString("strIdsInvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur maximale dépassée.
        /// </summary>
        internal static string strIdsInvalidLength {
            get {
                return ResourceManager.GetString("strIdsInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection document!.
        /// </summary>
        internal static string strIdsInvalidSelection {
            get {
                return ResourceManager.GetString("strIdsInvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        internal static string strIdsInvalidShapeSelection {
            get {
                return ResourceManager.GetString("strIdsInvalidShapeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is already open or it has been badly closed, do you want to force its opening?.
        /// </summary>
        internal static string strIdsProjectAlreadyOpen {
            get {
                return ResourceManager.GetString("strIdsProjectAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to the database will not be taken into account until after the application has been restarted.
        /// </summary>
        internal static string strIdsQuitNeeded {
            get {
                return ResourceManager.GetString("strIdsQuitNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active projects.
        /// </summary>
        internal static string strNoActiveProject {
            get {
                return ResourceManager.GetString("strNoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No navigation link!!!.
        /// </summary>
        internal static string strNoNavigateLink {
            get {
                return ResourceManager.GetString("strNoNavigateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number already exists, the change will be ignored !!!.
        /// </summary>
        internal static string strNumAlreadyExist {
            get {
                return ResourceManager.GetString("strNumAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object already linked, operation impossible !!!.
        /// </summary>
        internal static string strObjectAlreadyLinked {
            get {
                return ResourceManager.GetString("strObjectAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: {0} already exists.
        /// </summary>
        internal static string strPageAlreadyExist {
            get {
                return ResourceManager.GetString("strPageAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation ({0})|{1}.
        /// </summary>
        internal static string strPresentationExtension {
            get {
                return ResourceManager.GetString("strPresentationExtension", resourceCulture);
            }
        }
    }
}
